services:
  contacts-api:
    build:
      context: .
    env_file:
      - .env.prod
    image: aashishpal09/contacts-api:1.0.0
    container_name: contacts-api
    restart: always
    ports:
      - "5000:${PORT}"
    volumes:
      - ./logs:/app/logs